---
title: "MaskRCNN Analysis"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(ggplot2)
library(tidyr)
```

```{r}
pathModelData <- './cvdatasetutils/models/MaskRCNNAnalysis.csv'

modelData <- read.csv(pathModelData)%>%
  mutate(model_id=as.character(model_id))

models <- unique(modelData$model_id)
ids <- data.frame(model_id=models, id=1:length(models))

modelData <- modelData %>%
  inner_join(ids, by='model_id') %>%
  filter(mixed == 'False')

memData <- modelData %>%
  select(id, model_id, epoch, batch_n, gpu_total, gpu_used, gpu_free) %>%
  arrange(id, epoch, batch_n) %>%
  group_by(id) %>%
  mutate(step = row_number()) %>%
  select(-epoch, -batch_n)

lossData <- modelData %>%
  select(id, model_id, epoch, batch_n, loss, loss_classifier, loss_objectness, loss_mask, loss_box_reg, loss_rpn_box_reg) %>%
  arrange(id, epoch, batch_n) %>%
  group_by(id) %>%
  mutate(step = row_number()) %>%
  select(-epoch, -batch_n)
```

```{r}
modelData %>%
  group_by(id) %>%
  summarize(model_id=last(model_id), alpha=max(alpha), downs=max(downsampling), real_batch=last(batch_size)*last(batch_accumulator), 
            hidden=max(mask_hidden), maxTime=max(time/3600), minLoss=min(loss)/min(batch_accumulator), maxGpu=max(gpu_total),
            map_train=max(map_train), map_test=max(map_test)) %>%
  arrange(desc(map_train))
```

```{r, fig.width=14, fig.height=12}
globalLoss <- lossData %>%
  select(id, loss, step) %>%
  gather(lossType, value, -id, -step) %>%
  mutate(lossType = as.factor(lossType))

lossData %>%
  select(-loss, -model_id) %>%
  gather(lossType, value, -id, -step) %>%
  mutate(lossType = as.factor(lossType)) %>%
  ggplot(aes(x=step, y = value, color=lossType)) +
    facet_wrap(~ id, ncol=3) +
    geom_line(alpha=0.2) +
    geom_smooth(method="loess") +
    geom_smooth(data=globalLoss, method="loess")
```


```{r, fig.width=12, fig.height=15}
memData %>%
  gather(memType, value, -model_id, -step) %>%
  mutate(memType = as.factor(memType)) %>%
  ggplot(aes(x=step, y = value, color=memType)) +
    facet_wrap(~ model_id, ncol=3) +
    geom_line(alpha=0.2) +
    geom_smooth(method="loess")
```


## Finetuning models

```{r}
pathModels <- './cvdatasetutils/models/'
finetuneFiles <- list.files(pathModels, pattern=".*Finetune.*csv")

finetuneData <- data.frame()

for (file in finetuneFiles) {
  finetuneFileData <- read.csv(paste(pathModels, file, sep='/'))
  finetuneData <- rbind(finetuneData, finetuneFileData)
}

finetuneData <- finetuneData %>%
  arrange(epoch, batch_n) %>%
  mutate(model_id=as.character(model_id))
```


```{r}
finetuneData %>%
  group_by(model_id, dataset) %>%
  summarize(alpha=max(alpha), downs=max(downsampling), real_batch=last(batch_size)*last(batch_accumulator), 
            hidden=max(mask_hidden),minLoss=min(loss)/min(batch_accumulator),
            map_train_max=max(map_train), map_train_min=min(map_train), map_test_max=max(map_test), map_test_min=min(map_test))
```


```{r}
finetuneData %>%
  group_by(model_id, epoch, dataset) %>%
  summarize(loss=max(loss)) %>%
  ggplot(aes(x=epoch, y=loss, group=dataset, color=dataset)) +
    geom_line()
```
























